### PR TITLE
Next Version

### PR DESCRIPTION
**Pull request by StanleyMasinde**
The current version works, but it is not ready for heavy projects for the following reasons
- [x] No webhook security
- [x] No support for other providers like Bitbucket
- [x] Complex configuration
- [x] No real-time alerts on deployment errors probably via E-mail
- [x] It currently deploys even when the affected branch is not master
- [x] Lack Rest endpoint that can be used to perform some tasks* (Not important for now)

This PR seeks to address the issues above in order to make this tool scalable.
We can also have.

### CODE REVIEW

**Comment by azim254** [comment]
shell version pia ikuje

**Comment by StanleyMasinde** [comment]
> shell version pia ikuje
Hi @azim254 Shell kiaje? ndio nieke kwa roadmap?

**Comment by azim254** [comment]
> > shell version pia ikuje
> > Hi @azim254 Shell kiaje? ndio nieke kwa roadmap?

something that pulls anything automatic from GitHub written in shell without dependencies

**Comment by StanleyMasinde** [comment]
> > > shell version pia ikuje
> > > Hi @azim254 Shell kiaje? ndio nieke kwa roadmap?
> 
> something that pulls anything automatic from GitHub written in shell without dependencies

Hehe, I hear you but hakuna "Automatic pulls". This thing relies on webhooks sent by Github. Meaning you need to have an HTTP listener to listen for the webhook events and act on them. Doing with nodejs is a lot easier

**Comment by azim254** [comment]
> > > > shell version pia ikuje
> > > > Hi @azim254 Shell kiaje? ndio nieke kwa roadmap?
> > 
> > 
> > something that pulls anything automatic from GitHub written in shell without dependencies
> 
> Hehe, I hear you but hakuna "Automatic pulls". This thing relies on webhooks sent by Github. Meaning you need to have an HTTP listener to listen for the webhook events and act on them. Doing with nodejs is a lot easier

ooh got it nice

**Comment by StanleyMasinde** [comment]
> > > > > shell version pia ikuje
> > > > > Hi @azim254 Shell kiaje? ndio nieke kwa roadmap?
> > > 
> > > 
> > > something that pulls anything automatic from GitHub written in shell without dependencies
> > 
> > 
> > Hehe, I hear you but hakuna "Automatic pulls". This thing relies on webhooks sent by Github. Meaning you need to have an HTTP listener to listen for the webhook events and act on them. Doing with nodejs is a lot easier
> 
> ooh got it nice

Umeiva shell tujaribu kuunda HTTP server 🤣

**Pull request merged**
